#+TITLE: How to build GNU Emacs with Japanese IME patch on Windows
#+AUTHOR: Masanao Igarashi
#+EMAIL: syoux2@gmail.com
#+DATE: 2025/03/17
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  ja
#+OPTIONS: H:4 num:nil toc:nil ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: tex:t todo:t pri:nil tags:t texht:nil
#+OPTIONS: author:t creator:nil email:nil date:t

* IMEパッチなどを適用したGNU Emacsのビルド方法

IMEパッチとcmigemoを組み込み、ネイティブコンパイル機能が有効なemacsを作成します。スタティックリンクなバイナリになりますので、msys2をインストールしていない別のWindows環境でも、インストールディレクトリを丸ごとコピーするだけで動作します。

ネイティブコンパイル機能を有効にすると、オリジナルのemacsソースツリーでは、ビルドに失敗します。UCRT版のPKGBULDを参考にビルド可能な方法を探りました。

日本の組織内では、プロキシを経由するネット環境が多いと思います。そういう環境の人でもつまずきが少なくなるように書きました。64bit環境を想定しています。

** MSYS2のインストール

MSYS2のインストーラーを[[https://www.msys2.org/]]からダウンロードします。

インストールが終わると、スタートメニューには以下の5つが追加されます。

- MSYS2 UCRT 64-bit
- MSYS2 UCRT 32-bit
- MSYS2 MinGW 64-bit
- MSYS2 MinGW 32-bit
- MSYS2 MSYS

以下の説明では、インストール先を =C:\msys64= にしたものとします。

** MSYS2更新のためのプロキシの設定(optional)

プロキシを経由して外部に接続する環境において、MSYS2の更新を行うための設定です。必要なければ、読み飛ばしてください。

以下の内容で =/etc/profile.d/proxy.sh= ファイルを準備します。

#+BEGIN_EXAMPLE
PROXY="プロキシのIP:ポート番号"
export http_proxy="http://${PROXY}"
export https_proxy="http://${PROXY}"
export HTTP_PROXY="http://${PROXY}"
export HTTPS_PROXY="http://${PROXY}"

range0=$(echo ローカルIP.ローカルIP.ローカルIP.{1..255})
export no_proxy=127.0.0.1,localhost,${range0// /,}
export NO_PROXY=${no_proxy}
#+END_EXAMPLE

不幸にも中間者攻撃型のプロキシ環境の中にいて、偽ルート証明書がインストールされている場合は、 =pacman= の設定ファイルを編集し、証明書確認処理をオフにします。

#+BEGIN_EXAMPLE
vim /etc/pacman.conf
#+END_EXAMPLE

=XferCommand= の行を探し、 =wget= に =--no-check-certificate= オプションを追加します。

#+BEGIN_EXAMPLE
XferCommand = /usr/bin/wget --no-check-certificate --passive-ftp -c -O %o %u
#+END_EXAMPLE

Windowsのエディタで編集する場合、 =C:\msys64\etc\pacman.conf= を編集してください。

プロキシのホスト名やポート番号の情報は、利用する環境に合わせてください。プロキシの設定方法は他にも様々ありますので、お好みの方法でかまいません。

** MSYSやUCRT64の更新

メニューからMSYS2 MSYSを起動し =pacman= コマンドで更新します。

#+BEGIN_EXAMPLE
pacman -Syuu
#+END_EXAMPLE

パッケージデータベースの同期がはじまり、更新対象のパッケージが表示されます。

#+BEGIN_EXAMPLE
:: インストールを行いますか？  [Y/n]
#+END_EXAMPLE

と出力され、入力待ちとなりましたら =y= もしくは =Enter= を入力してください。
そうすると、パッケージのダウンロードが始まり更新処理が行われます。終わるまでしばらくお待ちください。

更新が終わって、以下のような警告が出力される場合があります。

#+BEGIN_EXAMPLE
警告 : terminate MSYS2 without returning to shell and check for updates again
警告 : for example close your terminal window instead of calling exit
#+END_EXAMPLE

これが表示されたらメッセージ通りに、一旦端末を閉じてから再度更新を行います。

すべての更新が完了すると、以下のように出力されます。

#+BEGIN_EXAMPLE
 何も行うことがありません
#+END_EXAMPLE

** Emacsのビルドに必要なパッケージのインストール

パッケージのインストールにも =pacman= コマンドを使います。

#+BEGIN_EXAMPLE
pacman -S --needed base-devel \
  mingw-w64-ucrt-x86_64-toolchain \
  mingw-w64-ucrt-x86_64-autotools \
  mingw-w64-ucrt-x86_64-xpm-nox \
  mingw-w64-ucrt-x86_64-libtiff \
  mingw-w64-ucrt-x86_64-giflib \
  mingw-w64-ucrt-x86_64-libpng \
  mingw-w64-ucrt-x86_64-libjpeg-turbo \
  mingw-w64-ucrt-x86_64-librsvg \
  mingw-w64-ucrt-x86_64-lcms2 \
  mingw-w64-ucrt-x86_64-jansson \
  mingw-w64-ucrt-x86_64-libxml2 \
  mingw-w64-ucrt-x86_64-gnutls \
  mingw-w64-ucrt-x86_64-zlib \
  mingw-w64-ucrt-x86_64-imagemagick \
  mingw-w64-ucrt-x86_64-libgccjit \
  mingw-w64-ucrt-x86_64-freetype \
  mingw-w64-ucrt-x86_64-tree-sitter \
  mingw-w64-ucrt-x86_64-libwinpthread \
  mingw-w64-ucrt-x86_64-sqlite3
#+END_EXAMPLE

=git= もインストールします。

#+BEGIN_EXAMPLE
$ pacman -S git
#+END_EXAMPLE

** ソースツリーの展開

以下、作業用ディレクトリを =~/emacs= とします。

#+BEGIN_EXAMPLE
mkdir ~/emacs
cd ~/emacs
#+END_EXAMPLE

*** Emacsソースツリーを展開

emacsのソースをダウンロードします。
ここ[[https://github.com/emacs-mirror/emacs/tags]]からダウンロード可能です。

#+BEGIN_EXAMPLE
wget https://github.com/emacs-mirror/emacs/archive/refs/tags/emacs-30.1.tar.gz
#+END_EXAMPLE

展開します。

#+BEGIN_EXAMPLE
tar xf emacs-30.1.tar.gz
#+END_EXAMPLE

=emacs-emacs-30.1= ディレクトリの下にソースツリーができます。

本リポジトリのパッチを取得します。gitを使う例を示しますが、[[https://github.com/msnoigrs/emacs-on-windows-patches]]からブラウザを使ってダウンロードしてもかまいません。

#+BEGIN_EXAMPLE
git clone https://github.com/msnoigrs/emacs-on-windows-patches.git
#+END_EXAMPLE

gitにプロキシの設定が必要な場合は、[[https://gist.github.com/evantoli/f8c23a37eb3558ab8765][Configure Git to use a proxy]]を参考にして設定してください。

パッチを適用します。

バージョン30.1の場合。

#+BEGIN_EXAMPLE
cd emacs-emacs-30.1
patch -p1 < ../emacs-on-windows-patches/00-emacs-30.1-w32-ime.patch
patch -p1 < ../emacs-on-windows-patches/01-emacs-30.1-disable-w32-ime.patch
patch -p1 < ../emacs-on-windows-patches/02-emacs-30.1-dontusereg.patch
patch -p1 < ../emacs-on-windows-patches/03-emacs-30.1-cmigemo.patch
patch -p1 < ../emacs-on-windows-patches/04-emacs-30.1-mingw32-remove-check.patch
patch -p1 < ../emacs-on-windows-patches/001-ucrt-30.1.patch
patch -p1 < ../emacs-on-windows-patches/manifest-utf8.patch
#+END_EXAMPLE

バージョン31.0.50の場合。

#+BEGIN_EXAMPLE
cd emacs
patch -p1 < ../emacs-on-windows-patches/00-emacs-20250317-w32-ime.patch
patch -p1 < ../emacs-on-windows-patches/01-emacs-20250317-disable-w32-ime.patch
patch -p1 < ../emacs-on-windows-patches/02-emacs-20250317-dontusereg.patch
patch -p1 < ../emacs-on-windows-patches/03-emacs-20250317-cmigemo.patch
patch -p1 < ../emacs-on-windows-patches/04-emacs-20250317-mingw32-remove-check.patch
patch -p1 < ../emacs-on-windows-patches/001-ucrt-20250317.patch
patch -p1 < ../emacs-on-windows-patches/manifest-utf8.patch
#+END_EXAMPLE

これでパッチ済みのソースツリーができあがります。
ここではすべてのパッチを適用していますが、使いたいものだけでもよいです。

*** w32-ime.elを取得

#+BEGIN_EXAMPLE
cd ..
git clone https://github.com/trueroad/w32-ime.el
#+END_EXAMPLE

=w32-ime.el= をコピーします。

#+BEGIN_EXAMPLE
cp w32-ime.el/w32-ime.el emacs-emacs-30.1/lisp/international/w32-ime.el
#+END_EXAMPLE

*** nkfソースツリーを展開(cmigemoを組み込む場合)

nkfが後のcmigemoのビルド時に必要ですので、準備します。

nkfのソースをダウンロードします。

#+BEGIN_EXAMPLE
wget http://iij.dl.osdn.jp/nkf/70406/nkf-2.1.5.tar.gz
tar xf nkf-2.1.5.tar.gz
#+END_EXAMPLE

*** cmigemoソースツリーを展開(cmigemoを組み込む場合)

cmigemoを組み込む場合に必要ですので、準備します。

#+BEGIN_EXAMPLE
git clone https://github.com/koron/cmigemo.git
#+END_EXAMPLE

cmigemoのビルド中に、SKK辞書のダウンロードが行われます。プロキシなどの事情により失敗する可能性がある場合、先にダウンロードしておくとよいです。

#+BEGIN_EXAMPLE
cd cmigemo/dict
wget http://openlab.ring.gr.jp/skk/dic/SKK-JISYO.L.gz
gzip -d SKK-JISYO.L.gz
#+END_EXAMPLE

** ビルド

#+BEGIN_note
ここからは、UCRT64の環境で作業します。
#+END_note

メニューからMSYS2 UCRT 64-bitを起動します。

*** nkfのビルド(cmigemoを組み込む場合)

nkfをビルドしてインストールします。

#+BEGIN_EXAMPLE
cd nkf-2.1.5
make
make install
#+END_EXAMPLE

=/usr/local/bin/nkf.exe= にインストールされます。

*** cmigemoのビルド(cmigemoを組み込む場合)

cmigemoをビルドしてインストールします。

#+BEGIN_EXAMPLE
cd ../cmigemo
./configure --prefix=/usr/local
make mingw-all
make mingw-install
#+END_EXAMPLE

=/usr/local/bin/cmigemo.exe= 、 =/usr/local/bin/migemo.dll= 、 =/usr/local/include/migemo.h= などがインストールされます。

*** Emacsのビルド

emacsをビルドしてインストールします。

#+BEGIN_EXAMPLE
export MAKEFLAGS=-j9
export CC=gcc
export CFLAGS="-march=native -mtune=native -O2 -pipe -static -s -g0 -fstack-protector-strong -Wp,-D__USE_MINGW_ANSI_STDIO=1 -I/usr/local/include -fno-optimize-sibling-calls -Wno-error=implicit-function-declaration"
export LDFLAGS="-s"
cd ../emacs-emacs-30.1
./autogen.sh
./configure --prefix=/c/emacs --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --with-modules --without-dbus --without-pop --with-wide-int --with-imagemagick --with-jpeg --with-png --with-rsvg --with-xml2 --with-xpm --without-compress-install --with-tree-sitter --with-native-compilation=aot --with-cmigemo
make actual-all
make install-strip prefix=/c/emacs
#+END_EXAMPLE

CFLAGSの値やconfigureのオプションは、環境とお好みに合わせて変更してください。
ここでは、staticビルドをしています。インストール先は、 =C:\emacs= にしています。

これでインストールは完了です。

*** migemoを利用する場合に必要なelisp

migemoを利用する場合は、 =load-path= に含まれるディレクトリに =cmigemo.el= と =migemo-isearch-auto-enable.el= を置いてください。
 =cmigemo.el= と =migemo-isearch-auto-enable.el= の使い方は、[[https://github.com/rzl24ozi/cmigemo-module/README.md]] に従います。

* emacsを起動してみる

=C:\emacs\bin\runemacs.exe= を起動します。

=HOME= 環境変数に設定された位置がホームディレクトリと評価されます。emacsから見たデフォルトのホームディレクトリは、 =C:\Users\ログインユーザー名\AppData\Roaming= です。
したがってデフォルトの設定ファイルの位置は =C:\Users\ログインユーザー名\AppData\Roaming\.emacs.d\init.el= です。
ちなみにMSYS2のホームディレクトリ =~/= は、 =C:\msys64\home\ログインユーザー名= です。同じ位置に揃える場合は、 =HOME= 環境変数を =C:\msys64\home\ログインユーザー名= に設定するとよいでしょう。
