#+TITLE: Misc Settings
#+AUTHOR: Masanao Igarashi
#+EMAIL: syoux2@gmail.com
#+DATE: 2026/04/07
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE: ja
#+OPTIONS: H:4 num:nil toc:nil ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: tex:t todo:t pri:nil tags:t texht:nil
#+OPTIONS: author:t creator:nil email:nil date:t

* Windows上のemacsを使用するときに、同時に設定しておくと便利かもしれないもの

** Cicaフォント

日本語フォントがM+ fonts由来で、Windowsで使っても綺麗な表示。Cicaフォントをインストールします。

https://github.com/miiton/Cica

** MyricaMフォント

以下の文書に記載されているフォントファイルをダウンロードして、Windowsにインストールします。

https://github.com/tomokuni/Myrica/blob/master/product/Myrica.md

#+BEGIN_EXAMPLE
% wget https://github.com/tomokuni/Myrica/raw/master/product/MyricaM.zip
#+END_EXAMPLE

展開して、Myrica.TTCをエクスプローラーで右クリックしてインストールしてください。

** Google日本語入力

google謹製IMEをインストールします。

https://www.google.co.jp/ime/

以下のgistにあるキー設定を行います。mozcでの設定例ですが、Google日本語入力においても有効です。

https://gist.github.com/msnoigrs/fb1c08a2580704966556364ef558c634

以下を実行すると設定画面が表示されます。

#+BEGIN_EXAMPLE
> "C:\Program Files (x86)\Google\Google Japanese Input\GoogleIMEJaTool.exe" --mode=config_dialog
#+END_EXAMPLE

emacsからは、mozc.el、mozc_emacs_helper.exe 経由でGoogle日本語入力を利用します。
mozc_emacs_helper.exeは自分でmozcをビルドするか、以下のページからダウンロードします。ビルド方法についても、以下のページが詳しいです。

https://w.atwiki.jp/ntemacs/pages/93.html

以下はmozcの設定例です。

#+begin_src emacs-lisp
(when (require 'mozc nil t)
  (if (eq system-type 'windows-nt)
      (setq mozc-helper-program-name "c:/msys64/usr/local/bin/mozc_emacs_helper.exe")
    (defun mozc-word-register ()
      (interactive)
      (start-process "wordregister" "GoogleIMEJaTool.exe" "c:/Program Files (x86)/Google/Google Japanese Input/GoogleIMEJaTool.exe" "--mode=word_register_dialog"))
    (defun mozc-word-register ()
      (interactive)
      (start-process "wordregister" "mozc_tool" "/usr/libexec/mozc/mozc_tool" "--mode=word_register_dialog")))
  (set-language-environment "Japanese")
  (setq default-input-method "japanese-mozc")
  (setq mozc-keymap-kana mozc-keymap-kana-101us)
  (global-set-key (kbd "C-<f7>") 'mozc-word-register)
  (global-set-key (kbd "<convert>")
                  (lambda () (interactive)
                    (mozc-mode 1)
                    (when (null current-input-method) (toggle-input-method))))
  (global-set-key (kbd "<non-convert>")
                  (lambda () (interactive)
                    (when current-input-method (deactivate-input-method)))))
#+end_src

** Ctrl+Shiftや右Alt+Shiftのホットキーを解除

#+BEGIN_QUOTE
Windowsの設定 左側「地域と言語」選択
「キーボードの詳細設定」
「言語バーのオプション」
「テキストサービスと入力言語」画面が表示される。
「キーの詳細設定」タブ
「キーシーケンスの変更(C)...」を選択して
「入力言語を切り替える」を(なし)に
#+END_QUOTE

** AutoHotkey

後述する StartEmacs.exe や、IMEをON/OFFするキーバインドを変更するために使用します。

*** AutoHotkeyのインストール

最新のAutoHotkeyはv2系ですが、exeコンバータであるAhk2Exeはv1系にのみ同梱されます。v1系とv2系両方をインストールします。

v2の最新は、https://github.com/Lexikos/AutoHotkey_L/releases からダウンロードしてインストールします。
v1系は、現在 v1.1.37.02 が最新です。https://github.com/AutoHotkey/AutoHotkey/releases/tag/v1.1.37.02

*** Ahk2Exe64.exeのビルド

https://github.com/AutoHotkey/Ahk2Exe をcloneして =Ank2Exe64.ahk= を実行すると、Exc Converterの画面が立ち上がります。Sourceに =Ank2Exe64.ahk= を指定して Convertボタンを押すと、 =Ank2Exe64.exe= が生成されます。
=C:\Program Files\AutoHotkey\Compiler\Ank2Exe64.exe= にコピーしてください。

** StartEmacs

以下の機能を実現するexeファイルをセットアップします。

- emacsから参照可能な外部コマンドを調整するために、PATH環境変数をemacs実行前に設定する
- デスクトップ上のショートカットアイコンにファイルをドロップすると、そのファイルをemacsで開く
- emacsを二重起動せず、すでに起動されている場合はそのemacsを使用する
- (オプション) 右クリックメニューにemacsから開くメニューを追加

詳しくは https://github.com/msnoigrs/startemacs を参照してください。

** IMEのON/OFFのホットキー設定

私は、Shiftキーを素早く押す動作に、IMEのON/OFFを割り当てています。
ただしemacsでは変換/無変換キーを押したことにして、mozc経由で日本語入力をON/OFFしています。

- 右Shiftキーを単体で押すと、IMEをON
- 左Shiftキーを単体で押すと、IMEをOFF

詳しくは [[https://github.com/msnoigrs/customhkwin]] を参照してください。

** Ctrl2Cap

Aキーの左隣のキーがCtrlじゃないキーボードを使用する場合、私にはこれが必須です。

[[https://docs.microsoft.com/en-us/sysinternals/downloads/ctrl2cap]]

** msys2で予めインストールしておく

#+BEGIN_EXAMPLE
% pacman -S mingw-w64-ucrt-x86_64-libgit2
% pacman -S p7zip
% pacman -S unzip
#+END_EXAMPLE

** libegit2

magitで利用されるlibegit2をMinGW環境でビルドする方法。

#+begin_example
pacman -S mingw-w64-ucrt-x86_64-cmake
git clone https://github.com/magit/libegit2
cd libegit2
git submodule init
git submodule update
make CMAKE_POLICY_VERSION_MINIMUM=3.5 CMAKE_INSTALL_PREFIX=/c/msys64 EMACS=/c/emacs/bin/emacs.exe
cd build
make install
cd ..
mkdir -p /c/emacs/share/emacs/site-lisp/libegit2/build
cp libgit.el libgit.elc /c/emacs/share/emacs/site-lisp/libegit2
cp build/libegit2.dll /c/emacs/share/emacs/site-lisp/libegit2/build
#+end_example
