#+TITLE: Misc Settings
#+AUTHOR: Masanao Igarashi
#+EMAIL: syoux2@gmail.com
#+DATE: 2024/01/17
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE: ja
#+OPTIONS: H:4 num:nil toc:nil ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: tex:t todo:t pri:nil tags:t texht:nil
#+OPTIONS: author:t creator:nil email:nil date:t

* Windows上のemacsを使用するときに、同時に設定しておくと便利かもしれないもの

** Cicaフォント

日本語フォントがM+ fonts由来で、Windowsで使っても綺麗な表示。Cicaフォントをインストールします。

https://github.com/miiton/Cica

** MyricaMフォント

以下の文書に記載されているフォントファイルをダウンロードして、Windowsにインストールします。

https://github.com/tomokuni/Myrica/blob/master/product/Myrica.md

#+BEGIN_EXAMPLE
% wget https://github.com/tomokuni/Myrica/raw/master/product/MyricaM.zip
#+END_EXAMPLE

展開して、Myrica.TTCをエクスプローラーで右クリックしてインストールしてください。

** Google日本語入力

google謹製IMEをインストールします。

https://www.google.co.jp/ime/

以下のgistにあるキー設定を行います。mozcでの設定例ですが、Google日本語入力においても有効です。

https://gist.github.com/msnoigrs/fb1c08a2580704966556364ef558c634

以下を実行すると設定画面が表示されます。

#+BEGIN_EXAMPLE
> "C:\Program Files (x86)\Google\Google Japanese Input\GoogleIMEJaTool.exe" --mode=config_dialog
#+END_EXAMPLE

** Ctrl+Shiftや右Alt+Shiftのホットキーを解除

#+BEGIN_QUOTE
Windowsの設定 左側「地域と言語」選択
「キーボードの詳細設定」
「言語バーのオプション」
「テキストサービスと入力言語」画面が表示される。
「キーの詳細設定」タブ
「キーシーケンスの変更(C)...」を選択して
「入力言語を切り替える」を(なし)に
#+END_QUOTE

** AutoHotkey

後述する StartEmacs.exe や、IMEをON/OFFするキーバインドを変更するために使用します。以下から最新のものをダウンロードして、インストールします。

https://github.com/Lexikos/AutoHotkey_L/releases

** StartEmacs

以下の機能を実現するexeファイルをセットアップします。

- emacsから参照可能な外部コマンドを調整するために、PATH環境変数をemacs実行前に設定する
- デスクトップ上のショートカットアイコンにファイルをドロップすると、そのファイルをemacsで開く
- emacsを二重起動せず、すでに起動されている場合はそのemacsを使用する
- (オプション) 右クリックメニューにemacsから開くメニューを追加

詳しくは https://github.com/msnoigrs/startemacs を参照してください。

** IMEのON/OFFのホットキー設定

私は、以下のホットキーを設定して使っています。

- 右Shiftキーを単体で押すと、IMEをON
- 左Shiftキーを単体で押すと、IMEをOFF

詳しくは [[https://github.com/msnoigrs/customhkwin]] を参照してください。

** Ctrl2Cap

Aキーの左隣のキーがCtrlじゃないキーボードを使用する場合、私にはこれが必須です。

[[https://docs.microsoft.com/en-us/sysinternals/downloads/ctrl2cap]]

** msys2で予めインストールしておく

#+BEGIN_EXAMPLE
% pacman -S mingw-w64-x86_64-libgit2
% pacman -S p7zip
% pacman -S unzip
#+END_EXAMPLE

** libegit2

magitで利用されるlibegit2をMinGW環境でビルドする方法。

#+begin_example
% pacman -S mingw64/mingw-w64-x86_64-cmake
% git clone https://github.com/magit/libegit2
% cd ligegit2
% make EMACS=/c/emacs/bin/emacs.exe
% cd build
% cmake .. -DCMAKE_INSTALL_PREFIX=/mingw64
% make install
% cd ..
% mkdir -p /c/emacs/share/emacs/site-lisp/libegit2/build
% cp libgit.el libgit.elc /c/emacs/share/emacs/site-lisp/libegit2
% cp libegit2.dll /c/emacs/share/emacs/site-lisp/libegit2/build
#+end_example
