#+TITLE: Japanese IME patch and others for building with MinGW on Windows
#+AUTHOR: Masanao Igarashi
#+EMAIL: syoux2@gmail.com
#+DATE: 2026/04/06
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  ja
#+OPTIONS: H:4 num:nil toc:nil ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: tex:t todo:t pri:nil tags:t texht:nil
#+OPTIONS: author:t creator:nil email:nil date:t

* GNU Emacs 30.2(あるいは31.0.50)をWindows向けにMSYS2(UCRT64)でコンパイルして使う人のためのパッチ

Windowsでemacsを自前コンパイルするためのパッチです。ビルド方法は[[https://github.com/msnoigrs/emacs-on-windows-patches/blob/master/BUILD.org][BUILD.org]]を参照してください。UCRT64環境でビルドします。
レジストリ登録処理削除パッチと、cmigemoパッチはお好みにより適用してください。その他のパッチは必須です。

自前でビルドしたくない場合は、msys2のパッケージリポジトリにUCRT版が準備されていますので、それをインストールするとよいでしょう。https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-emacs

過去にはIME関係のパッチも置いていましたが、emacsが異常終了してしまう現象が起きるようになったため除きました。日本語入力に関しては、mozc.elからgoogle日本語入力を利用する方法に切り替えました。

** 02-emacs-30.2-dontusereg.patch, 02-emacs-20250829-dontusereg.patch

addpm.exeの処理において各種パスのレジストリ登録処理を省きます。addpm.exeにはスタートメニューにemacsのショートカットを作成するといった機能があります。

** 03-emacs-30.2-cmigemo.patch, 03-emacs-20250829-cmigemo.patch

[[https://gist.github.com/37317c89325bfb3f02f4142c5764b7b5][emacs-26.1-rc1-cmigemo.diff]]と意味的に同じものです。

以下、[[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]]からの引用です。
#+BEGIN_QUOTE
[[http://hp.vector.co.jp/authors/VA052357/emacs.html][GNU emacs(x64)]]でダイナミックロード機能が独自に実装される前のcmigemo組み込み部分です。
#+END_QUOTE

cmigemoに関するパッチは、以下の情報由来のものです。

- [[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][about patches and how to build emacs on Windows. (Japanese)]] :: 日本語Windows向けのIMEパッチやcmigemoを組み込むためのパッチ情報と、Windows上でemacsをコンパイルして使うための情報が丁寧に記されています。

私はこのcmigemo組み込みパッチを好んで使っていますが、他に同rzl24ozi氏による[[https://github.com/rzl24ozi/cmigemo-module][dynamic module版]]を使う方法もあります。

オリジナルのcmigemo組み込みパッチは、 cmigemoコマンドの =--nonewline= オプション相当の機能が実現できません。このパッチでは =cmigemo-open= の2つ目の引数で指定できるようにしました。 =cmigemo.el= についても =cmigemo-open= を呼び出している箇所を修正しました。 =migemo-options= 変数に =--nonewline= か =-n= が含まれている場合に、 =cmigemo-open= の2つ目の引数が =t= となります。ちなみにオリジナルパッチでは =migemo-options= 変数は参照されませんでしたが、この修正によりこの目的でのみ参照します。

=--nonewline= 機能は、migemoの出力結果を利用してripgrepを呼び出す場合に使います。 =--nonewline= を指定しない場合、migemoが出力する正規表現にripgrep非互換の表現が含まれてしまいます。この修正をすることで =consult-ripgrep= をmigemoと組み合わせて利用することができます。

=cmigemo.el= =migemo-isearch-auto-enable.el= はこのリポジトリのものを利用してください。

** 04-emacs-30.2-mingw32-remove-check.patch, 04-emacs-20250829-mingw32-remove-check.patch

configureスクリプトで行われる、imagemagickとlibgccjitに対するチェック処理がWindowsでは正常に行われないため、それらチェック処理を省きます。

** 001-ucrt-30.2.patch, 001-ucrt-20250829.patch

UCRT版のソースに付属するパッチです。

** manifest-utf8.patch

emacsからプロセスを起動すると、UTF-8からCP932に変換されてしまう現象を回避するパッチです。manifestファイルにUTF-8を指定することで解決します。 =M-!= に続けて =echo '日本語'= を実行した結果が文字化けする場合には、この対処をすることで回避可能です。msys2で配布されているemacsバイナリでは文字化けしてしまいます。

この辺りの事情は以下のサイトが詳しいです。
- https://ujimushisradjp.hatenablog.jp/entry/2023/12/14/003216
- https://gist.github.com/trueroad/d309d1931100634c2cd1058a0620c663

* ビルド方法

ビルド方法は[[https://github.com/msnoigrs/emacs-on-windows-patches/blob/master/BUILD.org][BUILD.org]]を参照してください。

* Tree-sitterのモジュールDLLをビルドする

[[https://github.com/msnoigrs/emacs-on-windows-patches/blob/master/BUILD-tree-sitter-dll.org][BUILD-tree-sitter-dll.org]]を参照してください。

* Windows上のemacsを使用するときに、同時に設定しておくと便利かもしれないもの

[[https://github.com/msnoigrs/emacs-on-windows-patches/blob/master/MISC.org][MISC.org]]にまとめました。
