#+TITLE: Japanese IME patch and others for building with MinGW on Windows
#+AUTHOR: Masanao Igarashi
#+EMAIL: syoux2@gmail.com
#+DATE: 2025/02/14
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  ja
#+OPTIONS: H:4 num:nil toc:nil ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: tex:t todo:t pri:nil tags:t texht:nil
#+OPTIONS: author:t creator:nil email:nil date:t

* GNU Emacs 29.4(あるいは31.0.50)をWindows向けにMinGW(MSYS2)でコンパイルして使う人のためのパッチ - W32-IME組み込み

飛躍的に高速化したnative compileをするemacs、いわゆるgccemacsですが、Windowsでも自前でコンパイルすることで動作します。ビルド方法は[[https://github.com/msnoigrs/emacs-on-windows-patches/blob/master/BUILD.org][BUILD.org]]を参照してください。
今回からUCRT64環境でビルドすることにしました。

msys2のパッケージリポジトリには既にUCRT版が準備されていますので、以下のパッチを適用する必要がない場合は、それをインストールするとよいでしょう。https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-emacs

IMEやcmigemoに関するパッチは、以下の情報由来のものです。Emacs 29.4のソースに適用できるように作成してあります。

- [[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][about patches and how to build emacs on Windows. (Japanese)]] :: 日本語Windows向けのIMEパッチやcmigemoを組み込むためのパッチ情報と、Windows上でemacsをコンパイルして使うための情報が丁寧に記されています。

** 00-emacs-29.4-w32-ime.patch, 00-emacs-20250214-w32-ime.patch

[[https://gist.github.com/rzl24ozi/ee4457df2f54c5f3ca0d02b56e371233][emacs-26.1-rc1-w32-ime.diff]]と意味的に同じものです。

以下、[[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]]からの引用です。
#+BEGIN_QUOTE
[[http://hp.vector.co.jp/authors/VA052357/emacs.html][GNU emacs(x64)]]のIME関連部分を切り出したものです。

configureに以下のオプションを追加しています。\\
デフォルトでW32-IME, RECONVERSION, DOCUMENTFEEDが有効ですが無効にしたい場合に指定してください。
#+END_QUOTE
#+BEGIN_EXAMPLE
--without-w32-ime      : W32-IME無効(同時にRECONVERSION、DOCUMENTFEEDも無効)
--without-reconversion : RECONVERSION無効(同時にDOCUMENTFEEDも無効)
--without-documentfeed : DOCUMENTFEED無効
#+END_EXAMPLE

** 01-emacs-29.4-disable-w32-ime.patch, 01-emacs-20250214-disable-w32-ime.patch

[[https://gist.github.com/rzl24ozi/da3370acb767096ce11fe867c6d9da6a][emacs-26.1-rc1-disable-w32-ime.diff]]と意味的に同じものです。

以下、[[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]]からの引用です。
#+BEGIN_QUOTE
以下の関数を追加します。
#+END_QUOTE
#+BEGIN_EXAMPLE
(disable-w32-ime)    ; IME無効化(IMEをONにできなくなります)
(enable-w32-ime)     ; IME無効化を元に戻す
(w32-ime-disabled-p) ; IMEが無効化されている場合 t を返す
#+END_EXAMPLE

** 02-emacs-29.4-dontusereg.patch, 02-emacs-20250214-dontusereg.patch

addpm.exeの処理において各種パスのレジストリ登録処理を省きます。addpm.exeにはスタートメニューにemacsのショートカットを作成するといった機能があります。

** 03-emacs-29.4-cmigemo.patch, 03-emacs-20250214-cmigemo.patch

[[https://gist.github.com/37317c89325bfb3f02f4142c5764b7b5][emacs-26.1-rc1-cmigemo.diff]]と意味的に同じものです。

以下、[[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]]からの引用です。
#+BEGIN_QUOTE
[[http://hp.vector.co.jp/authors/VA052357/emacs.html][GNU emacs(x64)]]でダイナミックロード機能が独自に実装される前のcmigemo組み込み部分です。
#+END_QUOTE

私はこのcmigemo組み込みパッチを好んで使っていますが、他に同rzl24ozi氏による[[https://github.com/rzl24ozi/cmigemo-module][dynamic module版]]を使う方法もあります。

オリジナルのcmigemo組み込みパッチは、 cmigemoコマンドの =--nonewline= オプション相当の機能が実現できません。実現できるように =cmigemo-open= の2つ目の引数で指定できるように修正しました。 =cmigemo.el= も =cmigemo-open= を呼び出している箇所を修正しました。 =migemo-options= 変数に =--nonewline= か =-n= が含まれている場合に、 =cmigemo-open= の2つ目の引数が =t= となります。ちなみにオリジナルパッチでは =migemo-options= 変数は参照されませんでしたが、この修正によりこの目的でのみ参照します。

=--nonewline= 機能は、migemoの出力結果を利用してripgrepを呼び出す場合に使います。 =--nonewline= を指定しない場合、migemoが出力する正規表現にripgrep非互換の表現が含まれてしまいます。修正をすることで =consult-ripgrep= をmigemoと組み合わせて利用できるようになりました。

=cmigemo.el= =migemo-isearch-auto-enable.el= はこのリポジトリのものを利用してください。

** 04-emacs-29.4-mingw32-remove-check.patch, 04-emacs-20250214-mingw32-remove-check.patch

configureスクリプトで行われる、imagemagickとlibgccjitに対するチェック処理がWindowsでは正常に行われないため、それらチェック処理を省きます。

** 001-ucrt.patch, 001-ucrt-20250214.patch

UCRT版のソースに付属するパッチです。

** Fix-MinGW-build-with-GCC14-and-later.patch

MinGWのGCC14.1以降だとコンパイルに失敗する事象を回避します。
[[https://mail.gnu.org/archive/html/bug-gnu-emacs/2024-05/msg01179.html]]
[[https://github.com/emacs-mirror/emacs/commit/5216903ae6c3f91ebefb1152af40753f723cbc39]]

** manifest-utf8.patch

emacsからプロセスを起動すると、UTF-8からCP932に変換されてしまう現象を回避するパッチです。manifestファイルにUTF-8を指定することで解決します。 =M-!= に続けて =echo '日本語'= を実行した結果が文字化けする場合には、この対処をすることで回避可能です。msys2で配布されているemacsバイナリは同じ問題を含んでいます。

この辺りの事情は以下のサイトが詳しいです。
- https://ujimushisradjp.hatenablog.jp/entry/2023/12/14/003216
- https://gist.github.com/trueroad/d309d1931100634c2cd1058a0620c663

* ビルド方法

ビルド方法は[[https://github.com/msnoigrs/emacs-on-windows-patches/blob/master/BUILD.org][BUILD.org]]を参照してください。日本の組織内では、プロキシを経由するネット環境が多いと思います。そういう環境の方にもつまずきが少なくなるように書きました。64bit環境を想定しています。

* Windows上のemacsを使用するときに、同時に設定しておくと便利かもしれないもの

[[https://github.com/msnoigrs/emacs-on-windows-patches/blob/master/MISC.org][MISC.org]]にまとめました。
