#+TITLE: Japanese IME patch and others for building with MinGW on Windows
#+AUTHOR: Masanao Igarashi
#+EMAIL: syoux2@gmail.com
#+DATE: 2019/10/17
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  ja
#+OPTIONS: H:4 num:nil toc:nil ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: tex:t todo:t pri:nil tags:t texht:nil
#+OPTIONS: author:t creator:nil email:nil date:t

* GNU Emacs 26.3をWindows向けにMinGW(MSYS2)でコンパイルして使う人のためのパッチ

このリポジトリに含まれるパッチは、以下の二つの情報由来のものです。Emacs 26.3のソースに適用できるように作成してあります。

- [[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]] :: 日本語Windows向けのIMEパッチやcmigemoを組み込むためのパッチ情報と、Windows上でemacsをコンパイルして使うための情報が丁寧に記されています。
- [[https://github.com/m-parashar/emax64][emax64]] :: ImageMagick 7に対応したWindows版emacsが公開されています。[[https://github.com/politza/pdf-tools][pdf-tools]]も動作します。

** 00-emacs-26.3-w32-ime.patch

[[https://gist.github.com/rzl24ozi/ee4457df2f54c5f3ca0d02b56e371233][emacs-26.1-rc1-w32-ime.diff]]と意味的に同じものです。

以下、[[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]]からの引用です。
#+BEGIN_QUOTE
[[http://hp.vector.co.jp/authors/VA052357/emacs.html][GNU emacs(x64)]]のIME関連部分を切り出したものです。

configureに以下のオプションを追加しています。\\
デフォルトでW32-IME, RECONVERSION, DOCUMENTFEEDが有効ですが無効にしたい場合に指定してください。
#+END_QUOTE
#+BEGIN_EXAMPLE
--without-w32-ime      : W32-IME無効(同時にRECONVERSION、DOCUMENTFEEDも無効)
--without-reconversion : RECONVERSION無効(同時にDOCUMENTFEEDも無効)
--without-documentfeed : DOCUMENTFEED無効
#+END_EXAMPLE

** 01-emacs-26.3-disable-w32-ime.patch

[[https://gist.github.com/rzl24ozi/da3370acb767096ce11fe867c6d9da6a][emacs-26.1-rc1-disable-w32-ime.diff]]と意味的に同じものです。

以下、[[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]]からの引用です。
#+BEGIN_QUOTE
以下の関数を追加します。
#+END_QUOTE
#+BEGIN_EXAMPLE
(disable-w32-ime)    ; IME無効化(IMEをONにできなくなります)
(enable-w32-ime)     ; IME無効化を元に戻す
(w32-ime-disabled-p) ; IMEが無効化されている場合 t を返す
#+END_EXAMPLE

** 02-emacs-26.3-dontusereg.patch

addpm.exeの処理において各種パスのレジストリ登録処理を省きます。addpm.exeにはスタートメニューにemacsのショートカットを作成するといった機能があります。[[https://github.com/m-parashar/emax64][emax64]]由来です。

** 03-emacs-26.3-imagemagick7.patch

ImageMagick 7をサポートするためのパッチ。[[https://github.com/m-parashar/emax64][emax64]]由来です。

** 04-emacs-26.3-cmigemo.patch

[[https://gist.github.com/37317c89325bfb3f02f4142c5764b7b5][emacs-26.1-rc1-cmigemo.diff]]と意味的に同じものです。

以下、[[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]]からの引用です。
#+BEGIN_QUOTE
[[http://hp.vector.co.jp/authors/VA052357/emacs.html][GNU emacs(x64)]]でダイナミックロード機能が独自に実装される前のcmigemo組み込み部分です。
#+END_QUOTE

私はこのcmigemo組み込みパッチを好んで使っていますが、他に同rzl24ozi氏による[[https://github.com/rzl24ozi/cmigemo-module][dynamic module版]]を使う方法もあります。

* ビルド方法

ビルド方法については、[[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]]や[[https://github.com/chuntaro/NTEmacs64]]に詳しく書いてありますが、[[https://github.com/msnoigrs/emacs-on-windows-patches/blob/master/BUILD.org][こちら]]にも簡単に記します。日本の組織内では、プロキシを経由するネット環境が多いと思います。そういう環境の方にもつまずきが少なくなるように書きました。64bit環境を想定しています。
