#+TITLE: Japanese IME patch and others for building with MinGW on Windows
#+AUTHOR: Masanao Igarashi
#+EMAIL: syoux2@gmail.com
#+DATE: 2019/10/17
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  ja
#+OPTIONS: H:4 num:nil toc:nil ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: tex:t todo:t pri:nil tags:t texht:nil
#+OPTIONS: author:t creator:nil email:nil date:t

* GNU Emacs 28.0.xをWindows向けにMinGW(MSYS2)でコンパイルして使う人のためのパッチ

飛躍的に高速化したnative compileをするemacs、いわゆるgccemacsですが、Windowsでも自前でコンパイルすることで動作します。

IMEやcmigemoに関するパッチは、以下の情報由来のものです。Emacs 28のソースに適用できるように作成してあります。

- [[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][about patches and how to build emacs on Windows. (Japanese)]] :: 日本語Windows向けのIMEパッチやcmigemoを組み込むためのパッチ情報と、Windows上でemacsをコンパイルして使うための情報が丁寧に記されています。

** 00-emacs-28-w32-ime.patch

[[https://gist.github.com/rzl24ozi/ee4457df2f54c5f3ca0d02b56e371233][emacs-26.1-rc1-w32-ime.diff]]と意味的に同じものです。

以下、[[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]]からの引用です。
#+BEGIN_QUOTE
[[http://hp.vector.co.jp/authors/VA052357/emacs.html][GNU emacs(x64)]]のIME関連部分を切り出したものです。

configureに以下のオプションを追加しています。\\
デフォルトでW32-IME, RECONVERSION, DOCUMENTFEEDが有効ですが無効にしたい場合に指定してください。
#+END_QUOTE
#+BEGIN_EXAMPLE
--without-w32-ime      : W32-IME無効(同時にRECONVERSION、DOCUMENTFEEDも無効)
--without-reconversion : RECONVERSION無効(同時にDOCUMENTFEEDも無効)
--without-documentfeed : DOCUMENTFEED無効
#+END_EXAMPLE

** 01-emacs-28-disable-w32-ime.patch

[[https://gist.github.com/rzl24ozi/da3370acb767096ce11fe867c6d9da6a][emacs-26.1-rc1-disable-w32-ime.diff]]と意味的に同じものです。

以下、[[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]]からの引用です。
#+BEGIN_QUOTE
以下の関数を追加します。
#+END_QUOTE
#+BEGIN_EXAMPLE
(disable-w32-ime)    ; IME無効化(IMEをONにできなくなります)
(enable-w32-ime)     ; IME無効化を元に戻す
(w32-ime-disabled-p) ; IMEが無効化されている場合 t を返す
#+END_EXAMPLE

** 02-emacs-28-dontusereg.patch

addpm.exeの処理において各種パスのレジストリ登録処理を省きます。addpm.exeにはスタートメニューにemacsのショートカットを作成するといった機能があります。

** 03-emacs-28-cmigemo.patch

[[https://gist.github.com/37317c89325bfb3f02f4142c5764b7b5][emacs-26.1-rc1-cmigemo.diff]]と意味的に同じものです。

以下、[[https://gist.github.com/rzl24ozi/008d32c1f0742d3d2901295bf0366efa][abount patches and how to build emacs on Windows. (Japanese)]]からの引用です。
#+BEGIN_QUOTE
[[http://hp.vector.co.jp/authors/VA052357/emacs.html][GNU emacs(x64)]]でダイナミックロード機能が独自に実装される前のcmigemo組み込み部分です。
#+END_QUOTE

私はこのcmigemo組み込みパッチを好んで使っていますが、他に同rzl24ozi氏による[[https://github.com/rzl24ozi/cmigemo-module][dynamic module版]]を使う方法もあります。

** 04-emacs-28-mingw32-remove-check.patch

=configure= においてgccjitやimagemagickの存在確認チェック処理を無効にするパッチです。存在確認チェック処理が正しく機能しないため、 =--with-native-compilation= や =--with-imagemagick= を付した =configure= が止まってしまいます。(2021-12-15 時点)それを回避します。

* ビルド方法

ビルド方法は[[https://github.com/msnoigrs/emacs-on-windows-patches/blob/master/BUILD.org][BUILD.org]]を参照してください。日本の組織内では、プロキシを経由するネット環境が多いと思います。そういう環境の方にもつまずきが少なくなるように書きました。64bit環境を想定しています。

* Windows上のemacsを使用するときに、同時に設定しておくと便利かもしれないもの

[[https://github.com/msnoigrs/emacs-on-windows-patches/blob/master/MISC.org][MISC.org]]にまとめました。
